### ISSUE TITLE
Initial Figma Prototyping For About Page

### ISSUE THREAD

**Issue by armandoparra13** [sharingexcess/sharingexcess.com#29]
Based on the low-fidelity wireframes, add content to the design. Create plans for different micro-interactions when necessary (such as a "Meet the Team" preview), and create ideas for how the blog post thumbnails will be displayed.

**Comment by jiitra** [comment]
This week, I made the wireframes high-fidelity by using SE colors, images, components, and text, and I began planning the "Meet the Team" page. I also started prototyping for mobile design.

**Comment by jiitra** [comment]
Main page design is finished. Next steps are completing the related pages (Meet the Team, Impact, Partners) and finding / inserting actual photos & graphics.
